sudo: required

dist: trusty

branches:
  gh_pages: true

env:
  - TEST_SUITE=lint
  - TEST_SUITE=unit
  - TEST_SUITE=e2e

language: node_js

node_js: stable

cache:
  directories:
    - node_modules

before_install:
 - if [[ $TEST_SUITE = e2e ]]; export CHROME_BIN=/usr/bin/google-chrome; fi
 - if [[ $TEST_SUITE = e2e ]]; export DISPLAY=:99.0; fi
 - if [[ $TEST_SUITE = e2e ]]; sh -e /etc/init.d/xvfb start; fi
 - if [[ $TEST_SUITE = e2e ]]; sudo apt-get update; fi
 - if [[ $TEST_SUITE = e2e ]]; sudo apt-get install -y libappindicator1 fonts-liberation; fi
 - if [[ $TEST_SUITE = e2e ]]; wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb; fi
 - if [[ $TEST_SUITE = e2e ]]; sudo dpkg -i google-chrome*.deb; fi

script:
  - if [[ $TEST_SUITE = e2e ]]; jdk_switcher use oraclejdk8; fi
  - "npm run $TEST_SUITE"
